export const palavras = [
  'árvore', 'água', 'avó', 'amor', 'açúcar',
  'banana', 'bala', 'bebê', 'bolo', 'brasil',
  'cachorro', 'café', 'cama', 'carro', 'casa',
  'céu', 'chá', 'chão', 'chuva', 'colher',
  'computador', 'coração', 'dado', 'dia', 'dicionário',
  'dinheiro', 'doce', 'elefante', 'escola', 'faca',
  'festa', 'flor', 'fogo', 'fome', 'fruta',
  'gato', 'gelo', 'girafa', 'grande', 'gravata',
  'guarda-chuva', 'homem', 'hora', 'igreja', 'ilha',
  'janela', 'joelho', 'lápis', 'leão', 'leite',
  'livro', 'lua', 'maçã', 'mãe', 'mão',
  'mar', 'médico', 'mel', 'menino', 'mesa',
  'milho', 'música', 'nariz', 'noite', 'nuvem',
  'óculos', 'olho', 'ônibus', 'orelha', 'ouro',
  'pai', 'pão', 'papai', 'parque', 'pássaro',
  'peixe', 'pé', 'pequeno', 'pérola', 'pijama',
  'pimenta', 'pipoca', 'pó', 'porta', 'prato',
  'prédio', 'queijo', 'rádio', 'raiz', 'rei',
  'revista', 'rio', 'rosto', 'sábado', 'saco',
  'sal', 'sapato', 'sol', 'sonho', 'táxi',
  'telefone', 'tempo', 'tigre', 'tio', 'trem',
  'uva', 'vaca', 'vela', 'vento', 'verão',
  'vídeo', 'violão', 'vizinho', 'você', 'zebra',
  'abacaxi', 'abelha', 'abóbora', 'açougue', 'afta',
  'almofada', 'aluno', 'amarelo', 'amigo', 'âncora',
  'anel', 'anjo', 'anta', 'apartamento', 'aranha',
  'ártico', 'asa', 'ave', 'avião', 'azul',
  'babá', 'bagunça', 'balaio', 'bambu', 'bandeira',
  'banheiro', 'barco', 'barulho', 'batata', 'bebida',
  'bicicleta', 'bife', 'biscoito', 'boca', 'boneca',
  'borboleta', 'borracha', 'brinquedo', 'cabeça', 'cadeado',
  'cadeira', 'caderno', 'café-da-manhã', 'caju', 'calça',
  'calçada', 'cama', 'camisa', 'caneta', 'canivete',
  'canudo', 'capacete', 'caranguejo', 'cardápio', 'carnaval',
  'carroça', 'cartão', 'castelo', 'cavalo', 'cebola',
  'cesta', 'chaleira', 'chapéu', 'chave', 'chiclete',
  'chocolate', 'chupeta', 'cidade', 'cinema', 'cinto',
  'circo', 'clube', 'cobra', 'coco', 'coelho',
  'colar', 'colher', 'comida', 'computador', 'copo',
  'corrente', 'cortina', 'costela', 'couve', 'criança',
  'cruz', 'dente', 'dente-de-leão', 'dicionário', 'dinossauro',
  'doença', 'doutor', 'edifício', 'elefante', 'elevador',
  'email', 'escada', 'escorregador', 'espada', 'espanador',
  'espingarda', 'esponja', 'estádio', 'estante', 'estrela',
  'fada', 'farinha', 'faxina', 'fazenda', 'ferradura',
  'ferramenta', 'festa', 'ficha', 'fila', 'fim',
  'fio', 'fogueira', 'foguete', 'folha', 'fone',
  'fósforo', 'fralda', 'frasco', 'frente', 'frio',
  'fritura', 'fumaça', 'gaiola', 'galinha', 'galo',
  'garfo', 'garrafa', 'gaveta', 'girafa', 'giz',
  'golfe', 'gorila', 'grama', 'grampeador', 'grilo',
  'grito', 'guarda-roupa', 'guerreiro', 'haste', 'helicóptero',
  'hidrante', 'hidroavião', 'holofote', 'holograma', 'homem-aranha',
  'hora', 'hotel', 'ícone', 'idade', 'iglu',
  'ímã', 'impressora', 'índio', 'inglês', 'inseto',
  'internet', 'íris', 'janela', 'jantar', 'jardim',
  'jarra', 'jaqueta', 'jardineira', 'jegue', 'jerimum',
  'joaninha', 'jornal', 'jornalista', 'jorrada', 'jovem',
  'juiz', 'júri', 'lago', 'laje', 'lâmpada',
  'lanche', 'lápis', 'laranja', 'lareira', 'lavanda',
  'leão', 'leite', 'leme', 'lenço', 'lençol',
  'lente', 'liderança', 'limão', 'limpeza', 'linha',
  'lixo', 'lobo', 'lua', 'luva', 'máquina',
  'madeira', 'madrugada', 'maçã', 'mágico', 'mala',
  'maleta', 'mamãe', 'mamão', 'manga', 'mangueira',
  'manhã', 'manta', 'mapa', 'máquina', 'maracujá',
  'marcador', 'marcha', 'margarida', 'marido', 'máscara',
  'máscara', 'mastro', 'mata', 'meia', 'melancia',
  'melão', 'menina', 'mercado', 'mês', 'mexerica',
  'mochila', 'moeda', 'mola', 'morangao'];

export const alfBraille = {
  a: 1,
  b: 3,
  c: 9,
  d: 25,
  e: 17,
  f: 11,
  g: 27,
  h: 19,
  i: 10,
  j: 26,
  k: 5,
  l: 7,
  m: 13,
  n: 29,
  o: 21,
  p: 15,
  q: 31,
  r: 23,
  s: 14,
  t: 30,
  u: 37,
  v: 39,
  w: 58,
  x: 45,
  y: 61,
  z: 53,
};
